app = "krakentime-winter-paper-1452"
primary_region = "cdg"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"
  FFMPEG_PATH = "/usr/bin/ffmpeg"
  YTDL_PATH = "/usr/bin/yt-dlp"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]  # ← LIGNE AJOUTÉE POUR CORRIGER L'ERREUR

  [[http_service.checks]]
    grace_period = "45s"
    interval = "30s"      
    timeout = "10s"       
    method = "GET"
    path = "/health"

[[mounts]]
  source = "bot_data_volume"
  destination = "/app/data"

[processes]
  app = "node index.js"

# CRITIQUE : Plus de ressources pour la musique
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024  # Doublé pour les opérations audio